In [6]:
import pandas as pd

In [5]:
x = pd.read_xlsx("C:\\Users\\JEFF DESENVOLVEDOR\\Desktop\\materiais de repositorios git\\BaseServi‡osPrestados.xlsx") 
#abre o arquivo x no noteboook python
#obs. sempre colocar o caminho do arquivo entre aspas"" e duas barras // para separar as pastas no caminho do arquivo.

AttributeError: module 'pandas' has no attribute 'read_xlsx'

In [ ]:
x.duplicated().sum() #verifica se há linhas duplicadas no dataset x

np.int64(0)

In [ ]:
x.describe() #gera estatísticas descritivas do dataset x

,Unnamed: 0,ano,id_municipio,ibc,cobertura_pop_4g5g,fibra,densidade_smp,hhi_smp,densidade_scm,hhi_scm,adensamento_estacoes
count,22280.000000,22280.000000,2.228000e+04,22280.000000,22280.000000,22280.000000,22280.000000,22280.000000,22280.000000,22280.000000,22280.000000
mean,11139.500000,2022.500000,3.253591e+06,51.906346,80.004675,76.216338,59.923873,47.390619,16.617638,56.186131,16.150221
std,6431.826335,1.118059,9.848440e+05,13.865064,18.047806,40.896435,19.343919,25.059560,17.417516,20.941347,14.837588
min,0.000000,2021.000000,1.100015e+06,9.810000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,5569.750000,2021.750000,2.512101e+06,43.140000,68.548075,50.000000,46.220000,27.000000,3.850000,43.000000,6.700000
50%,11139.500000,2022.500000,3.146280e+06,54.310000,84.711650,100.000000,60.180000,50.000000,11.490000,60.000000,11.240000
75%,16709.250000,2023.250000,4.119202e+06,62.292500,95.494500,100.000000,74.562500,67.000000,23.330000,72.000000,20.050000
max,22279.000000,2024.000000,5.300108e+06,94.570000,120.030900,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000

In [ ]:
x.head() #mostra as primeiras 5 linhas do dataset x

,Unnamed: 0,ano,sigla_uf,id_municipio,ibc,cobertura_pop_4g5g,fibra,densidade_smp,hhi_smp,densidade_scm,hhi_scm,adensamento_estacoes
0,0,2024,RO,1100296,49.92,62.9831,100,44.00,51,23.87,47,25.39
1,1,2024,AC,1200351,16.28,30.3470,0,36.72,16,8.04,33,8.36
2,2,2024,AM,1300839,29.17,50.9133,50,26.62,7,0.65,71,17.47
3,3,2024,AM,1302207,20.06,53.3310,0,36.33,36,5.85,19,13.45
4,4,2024,PA,1501204,34.08,52.8200,100,20.46,15,2.85,52,6.26