In [ ]:
import pandas as pd

In [ ]:
x = pd.read_excel("C:\\Users\\JEFF DESENVOLVEDOR\\Desktop\\materiais de repositorios git\\BaseServi‡osPrestados.xlsx") 
#abre o arquivo x no noteboook python
#obs. sempre colocar o caminho do arquivo entre aspas"" e duas barras // para separar as pastas no caminho do arquivo.
#sempre se atentar a extensao do arquivo .xlsx .csv .txt etc. e alterar no codigo a extensao do arquivo que voce quer abrir.

In [ ]:
x.duplicated().sum() #verifica se há linhas duplicadas no dataset x

np.int64(0)

In [ ]:
x.describe() #gera estatísticas descritivas do dataset x

       ID Funcionário  ID Cliente  Tempo Total de Contrato (Meses)
count      237.000000  237.000000                       237.000000
mean        69.776371  160.485232                         9.654008
std         41.148715   94.354614                         2.985579
min          1.000000    1.000000                         4.000000
25%         36.000000   80.000000                         8.000000
50%         68.000000  161.000000                        10.000000
75%        103.000000  241.000000                        12.000000
max        150.000000  320.000000                        14.000000

In [ ]:
x.head() #mostra as primeiras 5 linhas do dataset x

,Codigo do Servico,ID Funcionário,ID Cliente,Tempo Total de Contrato (Meses)
0,OS0001,67,1,14
1,OS0002,17,2,12
2,OS0003,116,4,14
3,OS0004,37,5,8
4,OS0005,130,6,8